import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

import duaPage from '@/public/assets/dua-logo.svg'
import homePage from '@/public/assets/nav/home.svg'
import allDua from '@/public/assets/nav/alldua.svg'
import memorize from '@/public/assets/nav/memorize.svg'
import bookMark from '@/public/assets/nav/bookmark.svg'
import ruqyah from '@/public/assets/nav/ruqyah.svg'
import duaInfo from '@/public/assets/nav/dua-info.svg'
import books from '@/public/assets/nav/books.svg'
import iWantToSupport from '@/public/assets/support.svg'
import searchIcon from '@/public/assets/search.svg'
import profile from '@/public/assets/profile1.svg'
import languageIcon from '@/public/assets/sidebar/language.svg'
import general from '@/public/assets/sidebar/general.svg'
import fontSettings from '@/public/assets/sidebar/font.svg'


const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Ruqyah | All Duas Collection",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#f7f8fa]">
          <div className="grid grid-cols-12 grid-rows-12 gap-4 px-5 pt-5 h-screen">
            {/* ----start Left-bar--- */}
            <div className="row-span-full hidden xl:block w-[105px] ">
              <div
                id="left-bar"
                className="w-[100px] flex flex-col gap-y-5 overflow-hidden"
              >
                <div className="bg-white rounded-3xl px-4 dark:bg-dark-bg h-[95vh] overflow-y-auto scrollbar-thin overflow-x-hidden pb-16 border">
                  <div className="pt-7 mb-10 xl:mb-16 2xl:mb-16 3xl:mb-24 container ">
                    <Link href="/">
                      <Image
                        src={duaPage}
                        alt="dua-logo"
                        className="h-13 w-16 mx-auto drop-shadow-[#1fa45b] xl:mb-0 cursor-pointer"
                        width={20}
                        height={20}
                      />
                    </Link>
                  </div>
                  <Link href="/">
                    <div className="justify-center items-center  cursor-pointer my-2 flex flex-row w-full rounded-lg group">
                      <div className=" w-1 rounded-tl-lg rounded-bl-lg " />
                      <div className="p-2 flex flex-row justify-center items-center">
                        <div className=" bg-[#f7f8fa] dark:bg-dark-bg-dark flex p-2 rounded-full items-center h-10 w-10 justify-center">
                          <Image
                            src={homePage}
                            alt="/"
                            width={20}
                            height={20}
                          />
                        </div>
                        <h2 className="text-mute-grey-200 dark:text-dark-text style-Kalpurush text-sm text-start group-hover:text-[#1fa45b] font-medium " />
                      </div>
                    </div>
                  </Link>
                  <Link href="/alldua">
                    <div className="justify-center items-center  cursor-pointer my-2 flex flex-row w-full rounded-lg group">
                      <div className=" w-1 rounded-tl-lg rounded-bl-lg " />
                      <div className="p-2 flex flex-row justify-center items-center">
                        <div className=" bg-[#f7f8fa] dark:bg-dark-bg-dark flex p-2 rounded-full items-center h-10 w-10 justify-center">
                          <Image
                            src={allDua}
                            alt="/alldua"
                            width={20}
                            height={20}
                          />
                        </div>
                        <h2 className="text-mute-grey-200 dark:text-dark-text style-Kalpurush text-sm text-start group-hover:text-[#1fa45b] font-medium " />
                      </div>
                    </div>
                  </Link>
                  <Link href="/memorize">
                    <div className="justify-center items-center  cursor-pointer my-2 flex flex-row w-full rounded-lg group">
                      <div className=" w-1 rounded-tl-lg rounded-bl-lg " />
                      <div className="p-2 flex flex-row justify-center items-center">
                        <div className=" bg-[#f7f8fa] dark:bg-dark-bg-dark flex p-2 rounded-full items-center h-10 w-10 justify-center">
                          <Image
                            src={memorize}
                            alt="/memorize"
                            width={20}
                            height={20}
                          />
                        </div>
                        <h2 className="text-mute-grey-200 dark:text-dark-text style-Kalpurush text-sm text-start group-hover:text-[#1fa45b] font-medium " />
                      </div>
                    </div>
                  </Link>
                  <Link href="/bookmark">
                    <div className="justify-center items-center  cursor-pointer my-2 flex flex-row w-full rounded-lg group">
                      <div className=" w-1 rounded-tl-lg rounded-bl-lg " />
                      <div className="p-2 flex flex-row justify-center items-center">
                        <div className=" bg-[#f7f8fa] dark:bg-dark-bg-dark flex p-2 rounded-full items-center h-10 w-10 justify-center">
                          <Image
                            src={bookMark}
                            alt="/bookmark"
                            width={20}
                            height={20}
                          />
                        </div>
                        <h2 className="text-mute-grey-200 dark:text-dark-text style-Kalpurush text-sm text-start group-hover:text-[#1fa45b] font-medium " />
                      </div>
                    </div>
                  </Link>
                  <Link href="/ruqyah">
                    <div className="justify-center items-center  cursor-pointer my-2 flex flex-row w-full rounded-lg group">
                      <div className=" w-1 rounded-tl-lg rounded-bl-lg " />
                      <div className="p-2 flex flex-row justify-center items-center">
                        <div className=" bg-[#f7f8fa] dark:bg-dark-bg-dark flex p-2 rounded-full items-center h-10 w-10 justify-center">
                          <Image
                            src={ruqyah}
                            alt="/ruqyah"
                            width={20}
                            height={20}
                          />
                        </div>
                        <h2 className="text-mute-grey-200 dark:text-dark-text style-Kalpurush text-sm text-start group-hover:text-[#1fa45b] font-medium " />
                      </div>
                    </div>
                  </Link>
                  <Link href="/dua-info">
                    <div className="justify-center items-center  cursor-pointer my-2 flex flex-row w-full rounded-lg group">
                      <div className=" w-1 rounded-tl-lg rounded-bl-lg " />
                      <div className="p-2 flex flex-row justify-center items-center">
                        <div className=" bg-[#f7f8fa] dark:bg-dark-bg-dark flex p-2 rounded-full items-center h-10 w-10 justify-center">
                          <Image
                            src={duaInfo}
                            alt="/dua-info"
                            width={20}
                            height={20}
                          />
                        </div>
                        <h2 className="text-mute-grey-200 dark:text-dark-text style-Kalpurush text-sm text-start group-hover:text-[#1fa45b] font-medium " />
                      </div>
                    </div>
                  </Link>
                  <Link href="/books">
                    <div className="justify-center items-center  cursor-pointer my-2 flex flex-row w-full rounded-lg group">
                      <div className=" w-1 rounded-tl-lg rounded-bl-lg " />
                      <div className="p-2 flex flex-row justify-center items-center">
                        <div className=" bg-[#f7f8fa] dark:bg-dark-bg-dark flex p-2 rounded-full items-center h-10 w-10 justify-center">
                          <Image
                            src={books}
                            alt="/books"
                            width={20}
                            height={20}
                          />
                        </div>
                        <h2 className="text-mute-grey-200 dark:text-dark-text style-Kalpurush text-sm text-start group-hover:text-[#1fa45b] font-medium " />
                      </div>
                    </div>
                  </Link>
                  <div className="pt-12 w-16 h-14 flex items-center justify-center container">
                    <Link href="/support">
                      <Image
                        src={iWantToSupport}
                        alt="/support"
                        width={20}
                        height={20}
                        className="h-16 w-20 mx-auto drop-shadow-[#1fa45b] xl:mb-0 cursor-pointer"
                      />
                    </Link>
                  </div>
                </div>
              </div>
            </div>

            {/* ---End Left-bar--- */}

            {/* ---Start Top-bar--- */}
            <div className="col-span-full md:col-span-11 md:col-start-2 bg-white rounded-2xl  md:bg-transparent md:rounded-none ">
              {" "}
              <div className=" flex items-center h-full">
                <div className="w-5/6 flex justify-between h-full items-center">
                  <Link href="/">
                    <p className="md:text-xl xl:text-2xl hidden md:block ">
                      Dua Page
                    </p>
                  </Link>
                  <div className="sm:flex mr-16 hidden items-center">
                    <div className="relative w-full">
                      <input
                        className="border rounded-md sm:w-[250px] md:w-[350px] placeholder:text-mute-grey dark:placeholder:text-[#96a2b4] block placeholder:text-sm bg-white py-[0.75rem] pl-4 pr-12 shadow-sm focus:outline-none focus:border-[#1fa45b] focus:ring-[#1fa45b] focus:ring-1 sm:text-sm sm-max:dark:bg-dark-bg-lite md:dark:bg-dark-bg-dark dark:bg-dark-bg dark:placeholder:opacity-[.6] lg:dark:bg-dark-bg-dark"
                        type="text"
                        placeholder="Search by Dua Name"
                      />
                      <div className="absolute inset-y-1 right-2 flex items-center justify-center bg-gray-100 rounded-md p-3 cursor-pointer">
                        <Image
                          alt="search-icon"
                          src={searchIcon}
                          width={20}
                          height={20}
                          className=""
                        />
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-1/6 ">
                  <div className="flex justify-end items-center gap-4">
                    {" "}
                    <Image
                      src={profile}
                      alt="profile"
                      width={45}
                      height={45}
                    />
                    <svg
                      className="ml-2 mr-2"
                      width={10}
                      height={7}
                      viewBox="0 0 10 7"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M5.79241 5.97063C5.3921 6.49064 4.6079 6.49064 4.20759 5.97063L1.04322 1.85999C0.537025 1.20243 1.00579 0.25 1.83563 0.25L8.16437 0.250001C8.99421 0.250001 9.46298 1.20243 8.95678 1.86L5.79241 5.97063Z"
                        fill="#868686"
                      />
                    </svg>
                    <Image
                      src="/assets/tab/home/settings.svg"
                      className="xl: hidden"
                      alt="settings"
                      width={20}
                      height={20}
                    />
                  </div>
                </div>
              </div>
            </div>
            {/* ---End Top-bar--- */}

            {children}

            {/* ---start Right-bar--- */}
            <div className="col-span-2 row-span-11 h-[86vh] hidden xl:block  col-start-11 rounded-3xl bg-white border">
              <div className="pt-9 pb-6">
                <div className=" bg-white shadow-md rounded-lg p-4">
                  {/* Settings Header */}
                  <div className="text-center mb-6">
                    <h1 className="text-xl font-semibold text-gray-500">Settings</h1>
                  </div>

                  {/* Language Settings */}
                  <div className="bg-transparent rounded-lg mb-6 border border-gray-300 ">
                    <div className="flex justify-evenly gap-3 items-center mb-4 bg-gray-100 rounded-md ">
                      <div className=" flex p-2  justify-center items-center ">
                        <Image
                          src={languageIcon}
                          alt="language icon"
                          width="full"
                          height="auto"
                          className="text-green-400"
                        />
                      </div>
                      <p className=" font-semibold text-green-500 ">
                        Language Settings
                      </p>
                    </div>

                    {/* Language Buttons */}
                    <div className="flex justify-center  flex-col gap-2 w-1/2 mx-auto my-2">
                      <button className="w-full py-2 px-4 rounded-md bg-green-600 text-white text-center flex items-center justify-center mr-2">
                        English
                      </button>
                      <button className="w-full py-2 px-4 rounded-md bg-gray-200 text-gray-500  text-center flex items-center justify-center">
                        বাংলা
                      </button>
                    </div>

                  </div>

                  {/* General Settings */}
                  <div className="bg-gray-100 rounded-lg p-4 mb-4 flex items-center">
                    <div className="bg-gray-200 flex p-2 rounded-full justify-center items-center mr-4">
                      <Image
                        src={general}
                        alt="/general"
                        width="full"
                        height="auto"

                      />
                    </div>
                    <p className="text-gray-500 font-semibold">General Settings</p>
                  </div>

                  {/* Font Settings */}
                  <div className="bg-gray-100 rounded-lg p-4 mb-4 flex items-center">
                    <div className="bg-gray-200 flex p-2 rounded-full justify-center items-center mr-4">
                      <Image
                        src={fontSettings}
                        alt="/font"
                        width="full"
                        height="auto"

                      />
                    </div>
                    <p className="text-gray-500 font-semibold">Font Settings</p>
                  </div>

                  {/* Appearance Settings */}
                  <div className="bg-gray-100 rounded-lg p-4 flex items-center">
                    <div className="bg-gray-200 flex p-2 rounded-full justify-center items-center mr-4">
                      <Image
                        src={fontSettings}
                        alt="/appearance"
                        width="full"
                        height="auto"

                      />
                    </div>
                    <p className="text-gray-500 font-semibold">Appearance Settings</p>
                  </div>
                </div>
              </div>
            </div>
            {/* ---End Right-bar--- */}
          </div>
        </div>
      </body>
    </html>
  );
}
