import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

import duaPage from '@/public/assets/dua-logo.svg'
import homePage from '@/public/assets/nav/home.svg'
import allDua from '@/public/assets/nav/alldua.svg'
import memorize from '@/public/assets/nav/memorize.svg'
import bookMark from '@/public/assets/nav/bookmark.svg'
import ruqyah from '@/public/assets/nav/ruqyah.svg'
import duaInfo from '@/public/assets/nav/dua-info.svg'
import books from '@/public/assets/nav/books.svg'
import iWantToSupport from '@/public/assets/support.svg'


const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Ruqyah | All Duas Collection",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#f7f8fa]">
          <div className="grid grid-cols-12 grid-rows-12 gap-4 px-5 pt-5 h-screen">
            {/* ----start Left-bar--- */}
            <div className="row-span-full hidden xl:block w-[105px] ">
              <div
                id="left-bar"
                className="w-[100px] flex flex-col gap-y-5 overflow-hidden"
              >
                <div className="bg-white rounded-3xl px-4 dark:bg-dark-bg h-[95vh] overflow-y-auto scrollbar-thin overflow-x-hidden pb-16 border">
                  <div className="pt-7 mb-10 xl:mb-16 2xl:mb-16 3xl:mb-24 container ">
                    <Link href="/">
                      <Image
                        src={duaPage}
                        alt="dua-logo"
                        className="h-13 w-16 mx-auto drop-shadow-[#1fa45b] xl:mb-0 cursor-pointer"
                        width={20}
                        height={20}
                      />
                    </Link>
                  </div>
                  <Link href="/">
                    <div className="justify-center items-center  cursor-pointer my-2 flex flex-row w-full rounded-lg group">
                      <div className=" w-1 rounded-tl-lg rounded-bl-lg " />
                      <div className="p-2 flex flex-row justify-center items-center">
                        <div className=" bg-[#f7f8fa] dark:bg-dark-bg-dark flex p-2 rounded-full items-center h-10 w-10 justify-center">
                          <Image
                            src={homePage}
                            alt="/"
                            width={20}
                            height={20}
                          />
                        </div>
                        <h2 className="text-mute-grey-200 dark:text-dark-text style-Kalpurush text-sm text-start group-hover:text-[#1fa45b] font-medium " />
                      </div>
                    </div>
                  </Link>
                  <Link href="/alldua">
                    <div className="justify-center items-center  cursor-pointer my-2 flex flex-row w-full rounded-lg group">
                      <div className=" w-1 rounded-tl-lg rounded-bl-lg " />
                      <div className="p-2 flex flex-row justify-center items-center">
                        <div className=" bg-[#f7f8fa] dark:bg-dark-bg-dark flex p-2 rounded-full items-center h-10 w-10 justify-center">
                          <Image
                            src={allDua}
                            alt="/alldua"
                            width={20}
                            height={20}
                          />
                        </div>
                        <h2 className="text-mute-grey-200 dark:text-dark-text style-Kalpurush text-sm text-start group-hover:text-[#1fa45b] font-medium " />
                      </div>
                    </div>
                  </Link>
                  <Link href="/memorize">
                    <div className="justify-center items-center  cursor-pointer my-2 flex flex-row w-full rounded-lg group">
                      <div className=" w-1 rounded-tl-lg rounded-bl-lg " />
                      <div className="p-2 flex flex-row justify-center items-center">
                        <div className=" bg-[#f7f8fa] dark:bg-dark-bg-dark flex p-2 rounded-full items-center h-10 w-10 justify-center">
                          <Image
                            src={memorize}
                            alt="/memorize"
                            width={20}
                            height={20}
                          />
                        </div>
                        <h2 className="text-mute-grey-200 dark:text-dark-text style-Kalpurush text-sm text-start group-hover:text-[#1fa45b] font-medium " />
                      </div>
                    </div>
                  </Link>
                  <Link href="/bookmark">
                    <div className="justify-center items-center  cursor-pointer my-2 flex flex-row w-full rounded-lg group">
                      <div className=" w-1 rounded-tl-lg rounded-bl-lg " />
                      <div className="p-2 flex flex-row justify-center items-center">
                        <div className=" bg-[#f7f8fa] dark:bg-dark-bg-dark flex p-2 rounded-full items-center h-10 w-10 justify-center">
                          <Image
                            src={bookMark}
                            alt="/bookmark"
                            width={20}
                            height={20}
                          />
                        </div>
                        <h2 className="text-mute-grey-200 dark:text-dark-text style-Kalpurush text-sm text-start group-hover:text-[#1fa45b] font-medium " />
                      </div>
                    </div>
                  </Link>
                  <Link href="/ruqyah">
                    <div className="justify-center items-center  cursor-pointer my-2 flex flex-row w-full rounded-lg group">
                      <div className=" w-1 rounded-tl-lg rounded-bl-lg " />
                      <div className="p-2 flex flex-row justify-center items-center">
                        <div className=" bg-[#f7f8fa] dark:bg-dark-bg-dark flex p-2 rounded-full items-center h-10 w-10 justify-center">
                          <Image
                            src={ruqyah}
                            alt="/ruqyah"
                            width={20}
                            height={20}
                          />
                        </div>
                        <h2 className="text-mute-grey-200 dark:text-dark-text style-Kalpurush text-sm text-start group-hover:text-[#1fa45b] font-medium " />
                      </div>
                    </div>
                  </Link>
                  <Link href="/dua-info">
                    <div className="justify-center items-center  cursor-pointer my-2 flex flex-row w-full rounded-lg group">
                      <div className=" w-1 rounded-tl-lg rounded-bl-lg " />
                      <div className="p-2 flex flex-row justify-center items-center">
                        <div className=" bg-[#f7f8fa] dark:bg-dark-bg-dark flex p-2 rounded-full items-center h-10 w-10 justify-center">
                          <Image
                            src={duaInfo}
                            alt="/dua-info"
                            width={20}
                            height={20}
                          />
                        </div>
                        <h2 className="text-mute-grey-200 dark:text-dark-text style-Kalpurush text-sm text-start group-hover:text-[#1fa45b] font-medium " />
                      </div>
                    </div>
                  </Link>
                  <Link href="/books">
                    <div className="justify-center items-center  cursor-pointer my-2 flex flex-row w-full rounded-lg group">
                      <div className=" w-1 rounded-tl-lg rounded-bl-lg " />
                      <div className="p-2 flex flex-row justify-center items-center">
                        <div className=" bg-[#f7f8fa] dark:bg-dark-bg-dark flex p-2 rounded-full items-center h-10 w-10 justify-center">
                          <Image
                            src={books}
                            alt="/books"
                            width={20}
                            height={20}
                          />
                        </div>
                        <h2 className="text-mute-grey-200 dark:text-dark-text style-Kalpurush text-sm text-start group-hover:text-[#1fa45b] font-medium " />
                      </div>
                    </div>
                  </Link>
                  <div className="pt-12 w-16 h-14 flex items-center justify-center container">
                    <Link href="/support">
                      <Image
                        src={iWantToSupport}
                        alt="/support"
                        width={20}
                        height={20}
                        className="h-16 w-20 mx-auto drop-shadow-[#1fa45b] xl:mb-0 cursor-pointer"
                      />
                    </Link>
                  </div>
                </div>
              </div>
            </div>

            {/* ---End Left-bar--- */}

            {/* ---Start Top-bar--- */}
            <div className="col-span-full md:col-span-11 md:col-start-2 bg-white rounded-2xl  md:bg-transparent md:rounded-none ">
              {" "}
              <div className=" flex items-center h-full">
                <div className="w-5/6 flex justify-between h-full items-center">
                  <Link className="md:hidden" href="/">
                    <Image
                      src={duaPage}
                      alt="dua-logo"
                      className="h-12 w-12 md:hidden mx-auto drop-shadow-[#1fa45b] xl:mb-0 cursor-pointer"
                      width={20}
                      height={20}
                    />
                  </Link>
                  <p className="md:text-xl xl:text-2xl hidden md:block ">
                    Dua Page
                  </p>
                  <div className="sm:flex mr-16 hidden ">
                    <input
                      className=" border rounded-md mr-6  sm:w-[250px] md:w-[350px] placeholder:text-mute-grey dark:placeholder:text-[#96a2b4] block placeholder: placeholder:text-sm bg-white  py-[0.75rem] px-4 shadow-sm focus:outline-none focus:border-[#1fa45b] focus:ring-[#1fa45b] focus:ring-1  sm:text-sm sm-max:dark:bg-dark-bg-lite md:dark:bg-dark-bg-dark dark:bg-dark-bg dark:placeholder:opacity-[.6] lg:dark:bg-dark-bg-dark "
                      type="text"
                      placeholder="Search by Dua Name"
                    />
                    <div className="rounded-lg ml-[-70px]  flex justify-center items-center">
                      <Image
                        alt="search-icon"
                        src={"/assets/search-icon.svg"}
                        width={20}
                        height={20}
                        className=""
                      />
                    </div>
                  </div>
                </div>
                <div className="w-1/6 ">
                  <div className="flex justify-end items-center gap-4">
                    {" "}
                    <Image
                      src="/assets/settings/profile.svg"
                      alt="profile"
                      width={45}
                      height={45}
                    />
                    <svg
                      className="ml-2 mr-2"
                      width={10}
                      height={7}
                      viewBox="0 0 10 7"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M5.79241 5.97063C5.3921 6.49064 4.6079 6.49064 4.20759 5.97063L1.04322 1.85999C0.537025 1.20243 1.00579 0.25 1.83563 0.25L8.16437 0.250001C8.99421 0.250001 9.46298 1.20243 8.95678 1.86L5.79241 5.97063Z"
                        fill="#868686"
                      />
                    </svg>
                    <Image
                      src="/assets/tab/home/settings.svg"
                      className="xl: hidden"
                      alt="settings"
                      width={20}
                      height={20}
                    />
                  </div>
                </div>
              </div>
            </div>
            {/* ---End Top-bar--- */}

            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
